# Tensorflow Implementation of Style Loss

![style_loss](https://user-images.githubusercontent.com/63863911/191050886-14bdc139-6ef9-41c2-ba49-079f913b06b2.PNG)


In [1]:
import tensorflow as tf

In [2]:
x=tf.constant([1,2,3,4],shape=(2,2))

2022-09-19 15:14:25.989895: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [3]:
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [4]:
xt=tf.transpose(x)

In [5]:
xt

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

Using the ein function in linalg in tensorflow

In [6]:
tf.linalg.einsum('ij,ij->ij',x,x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

## Matrix multimlication using Einsum

In [7]:
tf.linalg.einsum('ij,jk->ik',xt,x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 14],
       [14, 20]], dtype=int32)>

In [8]:
tf.matmul(xt,x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 14],
       [14, 20]], dtype=int32)>

## Performing Reduced Sum

In [9]:
tf.linalg.einsum('ij,jk->',xt,x)

<tf.Tensor: shape=(), dtype=int32, numpy=58>

## Style Weight

The style weight is the calculated using the formula -->
1/(2*h*w*f) height , width and filters.
In our case with (2,2) matrix and the filter size be 1 , it will be..

In [10]:
1/(2*2*1)

0.25

## Final Code in Colab

![reduced sum](https://user-images.githubusercontent.com/63863911/191051170-63325e68-6b95-43e0-95c7-8f5e3188f5e5.PNG)
